<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-6LGB19CD" ignored="0" name="app测试" tests="2" failures="1" timestamp="2023-03-05T20:29:14 CST" time="177.067" errors="0">
  <testcase name="testShopCase01" time="46.066" classname="com.shucai.app.cases.ShopCase"/>
  <testcase name="testShopCase02" time="112.164" classname="com.shucai.app.cases.ShopCase">
    <failure type="java.lang.AssertionError" message="expected [1] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [1] but found [1]
at com.shucai.app.cases.ShopCase.testShopCase02(ShopCase.java:76)
at com.shucai.app.listener.AllureScreenShotListener.run(AllureScreenShotListener.java:18)
at java.util.ArrayList.forEach(ArrayList.java:1257)
... Removed 37 stack frames]]>
    </failure>
  </testcase> <!-- testShopCase02 -->
</testsuite> <!-- app测试 -->
